channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake-minimal==8.10.6
  - ncbi-amrfinderplus
  - python>=3.11
  - git
  - pip
  - pip:
      - pytest
      - pytest-cov
      - pytest-profiling
      - coverage 
      - pyopenssl==24.3.0
      - pyyaml
      - argh
      - watchdog
      - bifrostlib
      - -e .