channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake-minimal==5.7.1
  - ncbi-amrfinderplus
  - python>=3.6
  - git
  - pip
  - pip:
      - pytest
      - pytest-cov
      - pytest-profiling
      - coverage 
      - pyyaml
      - argh
      - watchdog
      - bifrostlib
      - -e .