#-Basic info----------------------------------------------------------------------------------------
display_name: amrfinderplus
name: &name amrfinderplus__v1.0.1
version:
  schema: ["v1.0.1"]
  code: v1.0.1

#-Details-------------------------------------------------------------------------------------------
details:
  target: [sample]
  description: >
    This performs AMRFinderPlus analysis on assembled contigs to detect acquired AMR genes
    and point mutations.

#-Category info-------------------------------------------------------------------------------------
category: [resistance]

#-Install-------------------------------------------------------------------------------------------
install:
  path:
  dockerfile: docker://ssidk/bifrost_amrfinderplus

#-Options-------------------------------------------------------------------------------------------
options:
  amrfinderplus_organism_option:
    "Campylobacter": [Campylobacter]
    "Campylobacter jejuni": [Campylobacter]
    "Campylobacter coli": [Campylobacter]
    "Campylobacter lari": [Campylobacter]
    "Campylobacter upsaliensis": [Campylobacter]
    "Campylobacter fetus": [Campylobacter]
    "Campylobacter helveticus": [Campylobacter]
    "Campylobacter sputorum": [Campylobacter]
    "Campylobacter concisus": [Campylobacter]
    "Campylobacter hyointestinalis": [Campylobacter]
    "Escherichia": [Escherichia]
    "Escherichia coli": [Escherichia]
    "Shigella": [Escherichia]
    "Shigella sonnei": [Escherichia]
    "Shigella flexneri": [Escherichia]
    "Shigella boydii": [Escherichia]
    "Shigella dysenteriae": [Escherichia]
    "Salmonella": [Salmonella]
    "Salmonella enterica": [Salmonella]
    "Salmonella bongori": [Salmonella]
    "Clostridioides difficile": [Clostridioides_difficile]
    "Other": [Other]

#-Required resource files---------------------------------------------------------------------------
resources:
  amrfinderplus_db: "/bifrost/components/bifrost_amrfinderplus/resources/amrfinderplus_db"

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    categories:
      contigs:
        summary:
          data:

#-DB Value changes----------------------------------------------------------------------------------
db_values_changes:
  files: []
  sample:
    categories:
      resistance:
        summary:
        component:
          _id:
          date:
    report:
      resistance:
        title: "Resistance"
        info: *name
        columns:
          - {id: "gene", name: "gene"}
          - {id: "coverage", name: "%cov"}
          - {id: "identity", name: "%id"}
          - {id: "variants", name: "# of variants"}
        data: []
  sample_component:
    summary:
      genes:
    results:
      amrfinderplus/data_yaml: {}
