name: AMRfinderplus workflow

on:
  push:
    branches: ["main","amr_dev"]
  pull_request:
    branches: ["main","amr_dev"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    steps:
      # step 1: checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 4: Extract version from __init__.py and set ENV_NAME
      - name: Set ENV_NAME
        run: |
          VERSION=$(grep "__version__" bifrost_amrfinderplus/__init__.py | cut -d "'" -f 2)
          REPO_NAME=$(basename "${{ github.workspace }}")
          ENV_NAME="${REPO_NAME}_v${VERSION}"
          # Echo the ENV_NAME to the log for debugging
          echo "Setting ENV_NAME to: $ENV_NAME"
          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_ENV
      
      # Step 4: Build Docker image
      - name: Build docker image
      run: |
        docker build --no-cache \
        --build-arg CONDA_ENV_NAME="${{ env.ENV_NAME }}" \
        -t bifrost_amrfinder_image .

      - name: Run_tests
      run: |
        docker run \
        --env CONDA_ENV_NAME="${{ env.ENV_NAME }}" \
        bifrost_amrfinder_image