name: AMRfinderplus workflow

on:
  push:
    branches: ["main","amr_dev"]
    tags-ignore:
      - "**"
  pull_request:
    branches: ["main","amr_dev"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    steps:
      # step 1: checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3